use keystone client instead of using openstacksdk conn
TypeError: _LabelWrapper.labels() got an unexpected keyword argument 'method' on iterating through conn.identity.projects() generator