Fix double-encoding error
The Python sendmail client performs text encoding so the input string
should be unicode and not bytes. Fixes error:

AttributeError: 'bytes' object has no attribute 'encode'