Notify project manager about projects violating lease stacking policy (#44)
* Notify project manager about projects violating lease stacking policy

Replaces lease stacking reaper with the notifier
We do not want to delete users' lease automatically if they are violating a policy.
Inform project manager about the violation and letting them take a decision is a valid thing to do.

This goes through blazar leases for cases of violations of lease stacking
and notifies them to project manager

This uses python-chi instead of osapi as it causing issues with authentication with openrc

* Use config instead of args

* remove old lease stack reaper

* use keystone client instead of using openstacksdk conn

TypeError: _LabelWrapper.labels() got an unexpected keyword argument 'method' on iterating through conn.identity.projects() generator

* use the start time for evaluation period as start of the first lease

* Better lease email formatting

* remove emails in testcases